# Generated by Django 5.2.1 on 2025-05-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_commentsentiment_delete_youtubecommentsentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsentiment',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
