# Generated by Django 5.2.1 on 2025-06-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_commentsentiment_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsentiment',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
